### PR TITLE
Add Permissions-Policy HTTP header to Caddyfile

### PR DESCRIPTION
**Pull request by zevlee**
The Feature-Policy header was renamed to Permissions-Policy. This PR simply includes this header to the Caddyfile.

See: https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

### CODE REVIEW

**Comment by unixfox** [comment]
Could you rename your commit name to a more describe name? This is for having a good git commit history in case we need to find this commit later.
I would rename it to something like this: "Add Permissions-Policy HTTP header". Feel free to offer something else.

**Comment by zevlee** [comment]
Just updated the title.

**Comment by unixfox** [comment]
I'm talking about the commit name not the pull request name.

**Comment by zevlee** [comment]
Changed the commit name this time. Thank you for your patience.

**Comment by unixfox** [comment]
Thank you for doing that but could you squash all your commits into one?

**Comment by unixfox** [comment]
Still 3 commits remaining :)

**Comment by zevlee** [comment]
I seem to have put myself in an unrecoverable position while learning about how to use git. As such, I will close this pull request and open a new one. Last time, I promise.

**Comment by unixfox** [comment]
No it's possible to always recover it, you really should do more git learning :).

**Pull request closed without merging**
